services:

  ead:
    container_name: client
    image: dasuntheek/codimates-client:latest
    ports:
      - "3000:3000"
    networks:
      - codimates-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  ead2:
    container_name: gateway
    image: dasuntheek/codimates-gateway:latest
    ports:
      - "4005:4005"
    networks:
      - codimates-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005"]
      interval: 10s
      timeout: 5s
      retries: 3

  ead3:
    container_name: user-service
    image: dasuntheek/codimates-user-service:latest
    ports:
      - "4001:4001"
    networks:
      - codimates-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001"]
      interval: 10s
      timeout: 5s
      retries: 3

  ead4:
    container_name: productandinventory
    image: dasuntheek/codimates-productandinventory:latest
    ports:
      - "4002:4002"
    networks:
      - codimates-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002"]
      interval: 10s
      timeout: 5s
      retries: 3

  ead5:
    container_name: order
    image: dasuntheek/codimates-order:latest
    ports:
      - "4004:4004"
    networks:
      - codimates-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004"]
      interval: 10s
      timeout: 5s
      retries: 3

  ead6:
    container_name: management
    image: dasuntheek/codimates-management:latest
    ports:
      - "3001:3001"
    networks:
      - codimates-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  codimates-network:
    driver: bridge