name: docker-compose-pipeline

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    name: Deploy images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List workspace files
        run: ls -la

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Create deployment folder
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p codimates"

      - name: Copy docker-compose file
        run: |
          scp -i ~/.ssh/id_rsa docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:codimates/docker-compose.yml

      - name: Set ENV variables and deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd codimates
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF
